CREATE TABLE IF NOT EXISTS Account (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(36) NOT NULL, -- Same code as AuthService user
    gender_id INT UNSIGNED,
    username VARCHAR(50) NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    country_id INT UNSIGNED,
    state_id INT UNSIGNED,
    city_id INT UNSIGNED,
    biography TEXT,
    date_of_birth DATE,
    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    profile_picture VARCHAR(255),
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (gender_id) REFERENCES Gender(id),
    FOREIGN KEY (country_id) REFERENCES Country(id),
    FOREIGN KEY (state_id) REFERENCES State(id),
    FOREIGN KEY (city_id) REFERENCES City(id),
    UNIQUE KEY up_account_code (code)
);